# 개발설정
spring:
  # DB접속정보
  datasource:
    url: jdbc:postgresql://localhost:15432/nexus_prod
    username: nexus
    password: nexus6993@@
    driver-class-name: org.postgresql.Driver
    
server:
  port: 4000

app:
  short-url:
    base-url: http://localhost:4000/s/    